import type { DiagramTemplate, TemplateNode, TemplateEdge } from "./index";

// Original layouts based on common public architecture/workflow patterns.
const node = (
  id: string,
  label: string,
  x: number,
  y: number,
  tone: TemplateNode["tone"] = "green",
  shape: TemplateNode["shape"] = "box",
  w = 180,
  h = 70,
  parent?: string,
): TemplateNode => ({ id, label, x, y, tone, shape, w, h, parent });
const lane = (
  id: string,
  label: string,
  x: number,
  y: number,
  w: number,
  h: number,
  tone: TemplateNode["tone"] = "gray",
) => node(id, label, x, y, tone, "lane", w, h);
const edge = (
  source: string,
  target: string,
  label?: string,
  from?: TemplateEdge["from"],
  to?: TemplateEdge["to"],
  via?: { x: number; y: number }[],
): TemplateEdge => ({ source, target, label, from, to, via });
const processon = {
  name: "ProcessOn · 架构图指南",
  url: "https://www.processon.com/framework",
};
const procurement = {
  name: "ProcessOn · 采购流程指南",
  url: "https://www.processon.com/knowledge/caigouliuchengtu",
};
const drawio = {
  name: "draw.io · 技术图例",
  url: "https://www.drawio.com/docs/diagram-types/",
};

const commerce: DiagramTemplate = {
  id: "commerce-platform",
  name: "电商平台全景架构",
  category: "architecture",
  complexity: "advanced",
  description:
    "覆盖多端接入、网关、六大业务域、数据基础设施和可观测性。包含同步调用、异步事件与核心存储关系。",
  tags: ["进阶", "业务分层", "微服务", "电商"],
  source: processon,
  nodes: [
    lane("channels", "01  用户触点与渠道", 20, 20, 1320, 150, "blue"),
    lane("access", "02  流量接入与安全边界", 20, 225, 1320, 150, "green"),
    lane(
      "domains",
      "03  业务服务 / 按领域独立演进",
      20,
      430,
      1320,
      155,
      "green",
    ),
    lane("data", "04  数据与异步基础设施", 20, 650, 1320, 155, "amber"),
    lane("ops", "05  服务治理与运维支撑", 20, 875, 1320, 155, "gray"),
    ...[
      "Web 商城\n消费者门户",
      "移动 App\niOS / Android",
      "微信小程序\n轻量交易入口",
      "商家工作台\n商品与履约",
      "开放 API\n合作伙伴",
    ].map((s, i) =>
      node(
        `channel${i}`,
        s,
        55 + i * 255,
        82,
        "blue",
        "box",
        230,
        64,
        "channels",
      ),
    ),
    ...[
      "CDN / WAF\n静态加速 · 安全防护",
      "负载均衡\n健康检查 · 流量分发",
      "API 网关\n路由 · 限流 · 熔断",
      "统一身份认证\nSSO · Token · 权限",
    ].map((s, i) =>
      node(
        `access${i}`,
        s,
        70 + i * 320,
        287,
        "green",
        "box",
        250,
        64,
        "access",
      ),
    ),
    ...[
      "用户中心\n账户 / 会员 / 地址",
      "商品中心\n商品 / 类目 / 定价",
      "交易中心\n订单 / 优惠 / 结算",
      "库存中心\n预占 / 扣减 / 释放",
      "支付中心\n支付 / 退款 / 对账",
      "履约中心\n仓配 / 物流 / 售后",
    ].map((s, i) =>
      node(
        `domain${i}`,
        s,
        45 + i * 215,
        492,
        "green",
        "box",
        195,
        70,
        "domains",
      ),
    ),
    ...[
      "业务数据库\n按服务隔离数据",
      "Redis 集群\n缓存 / 会话 / 库存",
      "搜索引擎\n商品索引 / 检索",
      "消息队列\n订单事件 / 重试",
      "对象存储\n图片 / 凭证 / 文件",
    ].map((s, i) =>
      node(
        `data${i}`,
        s,
        55 + i * 255,
        717,
        "amber",
        i < 3 ? "database" : "box",
        230,
        64,
        "data",
      ),
    ),
    ...[
      "注册与配置中心\n服务发现 / 动态配置",
      "链路追踪\n请求关联 / 调用耗时",
      "日志平台\n检索 / 审计 / 归档",
      "指标与告警\n错误率 / 延迟 / 容量",
      "CI/CD 平台\n测试 / 灰度 / 回滚",
    ].map((s, i) =>
      node(`ops${i}`, s, 55 + i * 255, 940, "gray", "box", 230, 64, "ops"),
    ),
  ],
  edges: [
    edge("channel0", "access0", undefined, "bottom", "top"),
    edge("channel1", "access1", undefined, "bottom", "top"),
    edge("channel2", "access2", undefined, "bottom", "top"),
    edge("channel3", "access2", undefined, "bottom", "top"),
    edge("channel4", "access3", undefined, "bottom", "top"),
    edge("access0", "access1"),
    edge("access1", "access2"),
    edge("access2", "access3", "鉴权"),
    ...Array.from({ length: 6 }, (_, i) =>
      edge("access2", `domain${i}`, undefined, "bottom", "top", [
        { x: 835, y: 402 },
        { x: 142.5 + i * 215, y: 402 },
      ]),
    ),
    edge("domain0", "data0", undefined, "bottom", "top"),
    edge("domain1", "data2", undefined, "bottom", "top", [
      { x: 357.5, y: 615 },
      { x: 680, y: 615 },
    ]),
    edge("domain2", "data0", "订单持久化", "bottom", "top", [
      { x: 572.5, y: 632 },
      { x: 170, y: 632 },
    ]),
    edge("domain3", "data1", undefined, "bottom", "top", [
      { x: 787.5, y: 604 },
      { x: 425, y: 604 },
    ]),
    edge("domain4", "data3", "支付事件", "bottom", "top"),
    edge("domain5", "data4", undefined, "bottom", "top"),
    edge("data3", "ops2", "消费与审计", "bottom", "top"),
    edge("data0", "ops3", "运行指标", "bottom", "top", [
      { x: 170, y: 845 },
      { x: 935, y: 845 },
    ]),
  ],
};

const kubernetes: DiagramTemplate = {
  id: "cloud-native",
  name: "云原生双可用区部署",
  category: "architecture",
  complexity: "advanced",
  description:
    "展示公网接入、两个可用区的容器工作负载、主从数据层，以及发布、监控、备份的运维路径。",
  tags: ["进阶", "Kubernetes", "高可用", "部署"],
  source: processon,
  nodes: [
    node("users", "互联网用户", 530, 20, "blue", "terminal", 220),
    node("dns", "DNS / CDN", 120, 150, "blue"),
    node("waf", "WAF / DDoS 防护", 500, 150, "blue", "box", 240),
    node("lb", "公网负载均衡", 980, 150, "blue", "box", 220),
    lane("az-a", "可用区 A / Kubernetes 工作节点", 20, 300, 575, 420, "green"),
    lane("az-b", "可用区 B / Kubernetes 工作节点", 675, 300, 575, 420, "blue"),
    node(
      "ingress-a",
      "Ingress A\nTLS / 路由",
      205,
      360,
      "green",
      "box",
      205,
      70,
      "az-a",
    ),
    node(
      "ingress-b",
      "Ingress B\nTLS / 路由",
      860,
      360,
      "blue",
      "box",
      205,
      70,
      "az-b",
    ),
    ...["a", "b"].flatMap((az, index) => [
      node(
        `api-${az}`,
        "API Service\nPod × 3",
        65 + index * 655,
        485,
        index ? "blue" : "green",
        "box",
        200,
        70,
        `az-${az}`,
      ),
      node(
        `worker-${az}`,
        "Worker Service\nPod × 2",
        335 + index * 655,
        485,
        index ? "blue" : "green",
        "box",
        200,
        70,
        `az-${az}`,
      ),
      node(
        `hpa-${az}`,
        "HPA 自动扩缩容",
        65 + index * 655,
        610,
        "gray",
        "box",
        200,
        60,
        `az-${az}`,
      ),
      node(
        `health-${az}`,
        "存活 / 就绪探针",
        335 + index * 655,
        610,
        "gray",
        "box",
        200,
        60,
        `az-${az}`,
      ),
    ]),
    lane("storage", "私有数据网络 / 数据持久化", 20, 820, 1230, 170, "amber"),
    node(
      "primary",
      "数据库主节点\n写入 / 事务",
      55,
      890,
      "amber",
      "database",
      235,
      70,
      "storage",
    ),
    node(
      "replica",
      "数据库从节点\n复制 / 故障切换",
      370,
      890,
      "amber",
      "database",
      235,
      70,
      "storage",
    ),
    node(
      "redis",
      "Redis 高可用集群\n缓存 / 会话",
      685,
      890,
      "amber",
      "database",
      235,
      70,
      "storage",
    ),
    node(
      "mq",
      "消息队列集群\n削峰 / 事件投递",
      1000,
      890,
      "amber",
      "box",
      210,
      70,
      "storage",
    ),
    lane("operations", "交付与可观测性", 1320, 300, 310, 690, "gray"),
    node(
      "pipeline",
      "CI/CD 流水线",
      1375,
      370,
      "gray",
      "box",
      200,
      65,
      "operations",
    ),
    node(
      "registry",
      "镜像仓库\n签名 / 漏洞扫描",
      1375,
      480,
      "gray",
      "box",
      200,
      70,
      "operations",
    ),
    node(
      "metrics",
      "监控 / 日志 / 追踪",
      1375,
      610,
      "gray",
      "box",
      200,
      70,
      "operations",
    ),
    node(
      "alerts",
      "值班告警\nSLO / 容量预警",
      1375,
      740,
      "rose",
      "box",
      200,
      70,
      "operations",
    ),
    node(
      "backup",
      "定时备份\n跨区恢复演练",
      1375,
      870,
      "gray",
      "box",
      200,
      70,
      "operations",
    ),
  ],
  edges: [
    edge("users", "dns", undefined, "left", "top"),
    edge("dns", "waf"),
    edge("waf", "lb"),
    edge("lb", "ingress-a", undefined, "bottom", "top", [
      { x: 1090, y: 265 },
      { x: 307.5, y: 265 },
    ]),
    edge("lb", "ingress-b", undefined, "bottom", "top"),
    ...(["a", "b"] as const).flatMap((az) => [
      edge(`ingress-${az}`, `api-${az}`, undefined, "bottom", "top"),
      edge(`api-${az}`, `worker-${az}`, "内部调用"),
      edge(`hpa-${az}`, `api-${az}`, "扩缩容", "top", "bottom"),
      edge(`health-${az}`, `worker-${az}`, "健康检查", "top", "bottom"),
    ]),
    edge("api-a", "primary", "读写", "left", "top", [
      { x: 40, y: 520 },
      { x: 40, y: 775 },
      { x: 172.5, y: 775 },
    ]),
    edge("api-b", "redis", "缓存", "left", "top", [
      { x: 655, y: 520 },
      { x: 655, y: 760 },
      { x: 802.5, y: 760 },
    ]),
    edge("worker-b", "mq", "消费", "right", "top", [
      { x: 1280, y: 520 },
      { x: 1280, y: 780 },
      { x: 1105, y: 780 },
    ]),
    edge("primary", "replica", "复制"),
    edge("pipeline", "registry"),
    edge("registry", "ingress-b", "滚动更新", "left", "right", [
      { x: 1290, y: 515 },
      { x: 1290, y: 395 },
    ]),
    edge("metrics", "alerts"),
    edge("primary", "backup", "备份", "bottom", "bottom", [
      { x: 172.5, y: 1050 },
      { x: 1475, y: 1050 },
    ]),
  ],
};

const purchase: DiagramTemplate = {
  id: "purchase-approval",
  name: "采购审批与验收泳道",
  category: "flow",
  complexity: "advanced",
  description:
    "四角色采购闭环：需求、预算、分级审批、询价、合同、验收、付款与归档，包含驳回和验收异常。",
  tags: ["进阶", "泳道图", "采购", "审批"],
  source: procurement,
  nodes: [
    lane("requester", "需求部门 / 提出需求与验收", 20, 20, 1740, 180, "blue"),
    lane("buying", "采购部门 / 供应商与合同", 20, 240, 1740, 180, "green"),
    lane("finance", "财务部门 / 预算与付款", 20, 460, 1740, 180, "amber"),
    lane("manager", "审批负责人 / 分级决策", 20, 680, 1740, 180, "rose"),
    node(
      "request",
      "提交采购申请",
      65,
      95,
      "blue",
      "box",
      180,
      65,
      "requester",
    ),
    node(
      "amend",
      "补充需求 / 预算",
      335,
      95,
      "blue",
      "box",
      180,
      65,
      "requester",
    ),
    node("receive", "到货核对", 1115, 95, "blue", "box", 180, 65, "requester"),
    node(
      "quality",
      "验收通过？",
      1380,
      73,
      "amber",
      "decision",
      160,
      110,
      "requester",
    ),
    node(
      "rejectgoods",
      "退换货处理",
      1570,
      95,
      "rose",
      "box",
      160,
      65,
      "requester",
    ),
    node(
      "review",
      "需求与物料核验",
      65,
      315,
      "green",
      "box",
      180,
      65,
      "buying",
    ),
    node("quote", "询价 / 比价", 595, 315, "green", "box", 180, 65, "buying"),
    node("supplier", "供应商评估", 845, 315, "green", "box", 180, 65, "buying"),
    node(
      "contract",
      "合同 / 采购订单",
      1115,
      315,
      "green",
      "box",
      180,
      65,
      "buying",
    ),
    node("deliver", "跟进供货", 1380, 315, "green", "box", 160, 65, "buying"),
    node(
      "budget",
      "预算充足？",
      65,
      510,
      "amber",
      "decision",
      180,
      110,
      "finance",
    ),
    node(
      "invoice",
      "发票 / 三单匹配",
      1115,
      535,
      "amber",
      "box",
      180,
      65,
      "finance",
    ),
    node("pay", "执行付款", 1380, 535, "amber", "box", 160, 65, "finance"),
    node(
      "archive",
      "凭证归档",
      1570,
      535,
      "gray",
      "terminal",
      160,
      65,
      "finance",
    ),
    node(
      "level",
      "超出审批额度？",
      65,
      730,
      "amber",
      "decision",
      180,
      110,
      "manager",
    ),
    node(
      "department",
      "部门负责人审批",
      335,
      750,
      "rose",
      "box",
      180,
      65,
      "manager",
    ),
    node("director", "总经理审批", 595, 750, "rose", "box", 180, 65, "manager"),
    node(
      "pass",
      "审批通过？",
      855,
      730,
      "amber",
      "decision",
      160,
      110,
      "manager",
    ),
    node("decline", "退回申请", 1115, 750, "rose", "box", 180, 65, "manager"),
  ],
  edges: [
    edge("request", "review"),
    edge("review", "budget"),
    edge("budget", "amend", "否", "right", "bottom", [
      { x: 295, y: 565 },
      { x: 295, y: 215 },
      { x: 425, y: 215 },
    ]),
    edge("amend", "request", "重新提交", "left", "right"),
    edge("budget", "level", "是"),
    edge("level", "department", "否"),
    edge("level", "director", "是", "bottom", "bottom", [
      { x: 155, y: 900 },
      { x: 685, y: 900 },
    ]),
    edge("department", "pass", undefined, "bottom", "bottom", [
      { x: 425, y: 880 },
      { x: 935, y: 880 },
    ]),
    edge("director", "pass"),
    edge("pass", "decline", "否"),
    edge("decline", "amend", "补充后重审", "right", "top", [
      { x: 1795, y: 782.5 },
      { x: 1795, y: 0 },
      { x: 425, y: 0 },
    ]),
    edge("pass", "quote", "是", "top", "bottom", [
      { x: 935, y: 675 },
      { x: 685, y: 675 },
    ]),
    edge("quote", "supplier"),
    edge("supplier", "contract"),
    edge("contract", "deliver"),
    edge("deliver", "receive", undefined, "top", "bottom", [
      { x: 1460, y: 220 },
      { x: 1205, y: 220 },
    ]),
    edge("receive", "quality"),
    edge("quality", "rejectgoods", "否"),
    edge("rejectgoods", "deliver", "重新交付", "bottom", "right", [
      { x: 1650, y: 347.5 },
    ]),
    edge("quality", "invoice", "是", "bottom", "right", [
      { x: 1460, y: 210 },
      { x: 1325, y: 210 },
      { x: 1325, y: 567.5 },
    ]),
    edge("invoice", "pay"),
    edge("pay", "archive"),
  ],
};

const order: DiagramTemplate = {
  id: "order-lifecycle",
  name: "订单交易与履约闭环",
  category: "flow",
  complexity: "advanced",
  description:
    "从下单、库存预占、支付回调到出库签收，并覆盖超时取消、幂等校验、库存释放、售后退款和对账。",
  tags: ["进阶", "订单", "异常分支", "支付"],
  source: drawio,
  nodes: [
    lane("checkout", "01  下单与库存预占", 20, 20, 1430, 180, "blue"),
    lane("payment", "02  支付与一致性", 20, 280, 1430, 210, "green"),
    lane("delivery", "03  履约与签收", 20, 570, 1430, 180, "amber"),
    lane("after", "04  售后与对账", 20, 830, 1430, 205, "rose"),
    node("cart", "购物车结算", 55, 95, "blue", "box", 170, 65, "checkout"),
    node(
      "verify",
      "校验价格 / 优惠",
      285,
      95,
      "blue",
      "box",
      180,
      65,
      "checkout",
    ),
    node("reserve", "预占库存", 525, 95, "blue", "box", 160, 65, "checkout"),
    node(
      "stockok",
      "库存充足？",
      750,
      72,
      "amber",
      "decision",
      150,
      110,
      "checkout",
    ),
    node(
      "created",
      "创建待支付订单",
      985,
      95,
      "blue",
      "box",
      190,
      65,
      "checkout",
    ),
    node(
      "soldout",
      "提示缺货",
      1225,
      95,
      "rose",
      "terminal",
      180,
      65,
      "checkout",
    ),
    node("pay", "发起支付", 55, 360, "green", "box", 170, 65, "payment"),
    node("callback", "支付回调", 285, 360, "green", "box", 180, 65, "payment"),
    node(
      "idempotent",
      "验签 / 幂等校验",
      525,
      360,
      "green",
      "box",
      160,
      65,
      "payment",
    ),
    node(
      "paid",
      "支付成功？",
      750,
      337,
      "amber",
      "decision",
      150,
      110,
      "payment",
    ),
    node(
      "commit",
      "确认订单 / 扣库存",
      985,
      360,
      "green",
      "box",
      190,
      65,
      "payment",
    ),
    node(
      "cancel",
      "超时关闭 / 释放库存",
      1225,
      360,
      "rose",
      "box",
      180,
      65,
      "payment",
    ),
    ...[
      "订单事件投递",
      "仓库拣货",
      "复核 / 打包",
      "出库 / 物流通知",
      "用户签收",
      "订单完成",
    ].map((s, i) =>
      node(
        `ship${i}`,
        s,
        55 + i * 232,
        645,
        "amber",
        "box",
        180,
        65,
        "delivery",
      ),
    ),
    node("claim", "申请售后", 55, 915, "rose", "box", 180, 65, "after"),
    node("review", "售后审核", 287, 915, "rose", "box", 180, 65, "after"),
    node(
      "accepted",
      "符合规则？",
      520,
      892,
      "amber",
      "decision",
      160,
      110,
      "after",
    ),
    node(
      "refund",
      "退货入库 / 退款",
      755,
      915,
      "rose",
      "box",
      180,
      65,
      "after",
    ),
    node(
      "reconcile",
      "日终账单核对",
      985,
      915,
      "green",
      "box",
      180,
      65,
      "after",
    ),
    node("manual", "差异人工处理", 1220, 915, "rose", "box", 180, 65, "after"),
    node("denied", "驳回并说明原因", 520, 1090, "rose", "terminal", 180, 65),
  ],
  edges: [
    edge("cart", "verify"),
    edge("verify", "reserve"),
    edge("reserve", "stockok"),
    edge("stockok", "created", "是"),
    edge("stockok", "soldout", "否", "top", "top", [
      { x: 825, y: 0 },
      { x: 1315, y: 0 },
    ]),
    edge("created", "pay", "等待支付", "bottom", "top", [
      { x: 1080, y: 245 },
      { x: 140, y: 245 },
    ]),
    edge("pay", "callback"),
    edge("callback", "idempotent"),
    edge("idempotent", "paid"),
    edge("paid", "commit", "是"),
    edge("paid", "cancel", "超时 / 失败", "top", "top", [
      { x: 825, y: 265 },
      { x: 1315, y: 265 },
    ]),
    edge("commit", "ship0", "事务提交后", "bottom", "top", [
      { x: 1080, y: 530 },
      { x: 145, y: 530 },
    ]),
    ...Array.from({ length: 5 }, (_, i) => edge(`ship${i}`, `ship${i + 1}`)),
    edge("ship4", "claim", "售后期内", "bottom", "top", [
      { x: 1073, y: 790 },
      { x: 145, y: 790 },
    ]),
    edge("claim", "review"),
    edge("review", "accepted"),
    edge("accepted", "refund", "是"),
    edge("accepted", "denied", "否", "bottom", "top"),
    edge("refund", "reconcile"),
    edge("reconcile", "manual", "不一致"),
  ],
};

const warehouse: DiagramTemplate = {
  id: "warehouse-platform",
  name: "实时离线数据仓库",
  category: "data",
  complexity: "advanced",
  description:
    "区分实时和离线数据链路，覆盖 ODS、DWD、DWS、ADS 分层，以及元数据、质量、权限和调度治理。",
  tags: ["进阶", "数仓分层", "实时计算", "数据治理"],
  source: processon,
  nodes: [
    lane("sources", "业务数据源", 20, 20, 1290, 145, "blue"),
    lane("ingestion", "采集与传输 / 批流分离", 20, 230, 1290, 145, "green"),
    lane("compute", "加工与数仓分层", 20, 445, 1290, 280, "amber"),
    lane("serving", "数据服务与应用", 20, 805, 1290, 150, "green"),
    lane("governance", "贯穿全链路的数据治理", 1390, 20, 300, 935, "gray"),
    ...[
      "交易数据库\n订单 / 支付",
      "行为日志\n点击 / 曝光",
      "业务系统 API\nCRM / ERP",
      "文件与外部数据\n报表 / 第三方",
    ].map((s, i) =>
      node(
        `source${i}`,
        s,
        65 + i * 315,
        80,
        "blue",
        "box",
        235,
        65,
        "sources",
      ),
    ),
    node("cdc", "CDC 增量订阅", 65, 290, "green", "box", 235, 65, "ingestion"),
    node(
      "kafka",
      "Kafka 事件总线",
      380,
      290,
      "green",
      "box",
      235,
      65,
      "ingestion",
    ),
    node(
      "batch",
      "离线批量抽取",
      695,
      290,
      "green",
      "box",
      235,
      65,
      "ingestion",
    ),
    node(
      "landing",
      "原始文件落地",
      1010,
      290,
      "green",
      "box",
      235,
      65,
      "ingestion",
    ),
    node(
      "ods",
      "ODS 原始层\n保留源数据",
      65,
      510,
      "amber",
      "database",
      235,
      70,
      "compute",
    ),
    node(
      "dwd",
      "DWD 明细层\n清洗 / 去重 / 标准化",
      380,
      510,
      "amber",
      "database",
      235,
      70,
      "compute",
    ),
    node(
      "dws",
      "DWS 汇总层\n主题聚合 / 指标口径",
      695,
      510,
      "amber",
      "database",
      235,
      70,
      "compute",
    ),
    node(
      "ads",
      "ADS 应用层\n业务宽表 / 数据集市",
      1010,
      510,
      "amber",
      "database",
      235,
      70,
      "compute",
    ),
    node(
      "stream",
      "实时计算\n窗口 / 水位 / 状态",
      65,
      625,
      "blue",
      "box",
      235,
      65,
      "compute",
    ),
    node(
      "olap",
      "实时 OLAP\n低延迟查询",
      380,
      625,
      "blue",
      "database",
      235,
      65,
      "compute",
    ),
    node(
      "dim",
      "DIM 维度模型\n用户 / 商品 / 时间",
      695,
      625,
      "amber",
      "database",
      235,
      65,
      "compute",
    ),
    node(
      "scheduler",
      "离线计算任务\n依赖 / 补数 / 重跑",
      1010,
      625,
      "amber",
      "box",
      235,
      65,
      "compute",
    ),
    ...[
      "经营驾驶舱\n核心指标 / 趋势",
      "自助 BI 分析\n维度钻取 / 报表",
      "数据服务 API\n统一查询出口",
      "特征与模型\n训练 / 在线推断",
    ].map((s, i) =>
      node(`app${i}`, s, 65 + i * 315, 865, "green", "box", 235, 65, "serving"),
    ),
    ...[
      "元数据与血缘",
      "数据质量规则",
      "数据目录 / 指标",
      "分级分类 / 脱敏",
      "访问权限 / 审计",
      "任务调度 / 告警",
    ].map((s, i) =>
      node(
        `gov${i}`,
        s,
        1430,
        100 + i * 140,
        "gray",
        "box",
        220,
        70,
        "governance",
      ),
    ),
  ],
  edges: [
    edge("source0", "cdc"),
    edge("source1", "kafka"),
    edge("source2", "batch"),
    edge("source3", "landing"),
    edge("cdc", "kafka"),
    edge("batch", "ods", undefined, "bottom", "top", [
      { x: 812.5, y: 410 },
      { x: 182.5, y: 410 },
    ]),
    edge("landing", "ods", undefined, "bottom", "top", [
      { x: 1127.5, y: 392 },
      { x: 182.5, y: 392 },
    ]),
    edge("ods", "dwd"),
    edge("dwd", "dws"),
    edge("dws", "ads"),
    edge("kafka", "stream", "实时", "left", "left", [
      { x: 35, y: 322.5 },
      { x: 35, y: 657.5 },
    ]),
    edge("stream", "olap"),
    edge("dim", "dws", "维度关联", "top", "bottom"),
    edge("scheduler", "ads", "调度", "top", "bottom"),
    edge("olap", "app0", undefined, "bottom", "top", [
      { x: 497.5, y: 770 },
      { x: 182.5, y: 770 },
    ]),
    edge("ads", "app1", undefined, "right", "top", [
      { x: 1340, y: 545 },
      { x: 1340, y: 790 },
      { x: 497.5, y: 790 },
    ]),
    edge("ads", "app2", undefined, "right", "top", [
      { x: 1360, y: 545 },
      { x: 1360, y: 770 },
      { x: 812.5, y: 770 },
    ]),
    edge("scheduler", "app3", undefined, "bottom", "top"),
  ],
};

const release: DiagramTemplate = {
  id: "release-pipeline",
  name: "灰度发布与回滚流水线",
  category: "flow",
  complexity: "advanced",
  description:
    "覆盖代码评审、质量门禁、安全扫描、集成验收、灰度观测、全量发布与回滚，适合团队发布规范。",
  tags: ["进阶", "CI/CD", "质量门禁", "灰度发布"],
  source: drawio,
  nodes: [
    lane("dev", "01  开发与评审", 20, 20, 1400, 160, "blue"),
    lane("ci", "02  持续集成 / 质量门禁", 20, 240, 1400, 190, "green"),
    lane("staging", "03  预发布环境 / 验收", 20, 500, 1400, 175, "amber"),
    lane("prod", "04  生产环境 / 灰度与回滚", 20, 750, 1400, 205, "rose"),
    ...["提交代码", "创建合并请求", "代码评审", "分支合并", "触发流水线"].map(
      (s, i) =>
        node(`dev${i}`, s, 65 + i * 275, 88, "blue", "box", 215, 65, "dev"),
    ),
    node("compile", "编译 / 单元测试", 65, 315, "green", "box", 215, 65, "ci"),
    node("scan", "依赖与安全扫描", 340, 315, "green", "box", 215, 65, "ci"),
    node(
      "gate",
      "质量门禁通过？",
      635,
      290,
      "amber",
      "decision",
      175,
      115,
      "ci",
    ),
    node("image", "构建 / 签名镜像", 890, 315, "green", "box", 215, 65, "ci"),
    node("registry", "推送制品仓库", 1165, 315, "green", "box", 215, 65, "ci"),
    ...[
      "部署预发布环境",
      "集成 / 回归测试",
      "业务验收 / 审批",
      "数据库变更核验",
      "生成发布清单",
    ].map((s, i) =>
      node(
        `stage${i}`,
        s,
        65 + i * 275,
        570,
        "amber",
        "box",
        215,
        65,
        "staging",
      ),
    ),
    node("canary", "灰度 5% 流量", 65, 835, "rose", "box", 215, 65, "prod"),
    node(
      "observe",
      "观测错误率 / 延迟",
      340,
      835,
      "rose",
      "box",
      215,
      65,
      "prod",
    ),
    node("slo", "指标正常？", 635, 810, "amber", "decision", 175, 115, "prod"),
    node(
      "rollout",
      "逐步扩大至全量",
      890,
      835,
      "green",
      "box",
      215,
      65,
      "prod",
    ),
    node(
      "finish",
      "发布完成 / 通知",
      1165,
      835,
      "green",
      "terminal",
      215,
      65,
      "prod",
    ),
    node("fix", "修复问题并重新提交", 65, 1040, "rose", "box", 240, 65),
    node("rollback", "停止放量 / 回滚版本", 525, 1040, "rose", "box", 240, 65),
    node("incident", "记录故障 / 复盘改进", 925, 1040, "gray", "box", 240, 65),
  ],
  edges: [
    ...Array.from({ length: 4 }, (_, i) => edge(`dev${i}`, `dev${i + 1}`)),
    edge("dev4", "compile", undefined, "bottom", "top", [
      { x: 1272.5, y: 210 },
      { x: 172.5, y: 210 },
    ]),
    edge("compile", "scan"),
    edge("scan", "gate"),
    edge("gate", "image", "是"),
    edge("image", "registry"),
    edge("gate", "fix", "否", "bottom", "left", [
      { x: 722.5, y: 455 },
      { x: 0, y: 455 },
      { x: 0, y: 1072.5 },
    ]),
    edge("registry", "stage0", undefined, "bottom", "top", [
      { x: 1272.5, y: 465 },
      { x: 172.5, y: 465 },
    ]),
    ...Array.from({ length: 4 }, (_, i) => edge(`stage${i}`, `stage${i + 1}`)),
    edge("stage4", "canary", undefined, "bottom", "top", [
      { x: 1272.5, y: 715 },
      { x: 172.5, y: 715 },
    ]),
    edge("canary", "observe"),
    edge("observe", "slo"),
    edge("slo", "rollout", "是"),
    edge("rollout", "finish"),
    edge("slo", "rollback", "否", "bottom", "top"),
    edge("rollback", "incident"),
    edge("fix", "dev0", "重跑", "left", "left", [
      { x: -30, y: 1072.5 },
      { x: -30, y: 120.5 },
    ]),
  ],
};

export const advancedTemplates = [
  commerce,
  kubernetes,
  purchase,
  order,
  warehouse,
  release,
];
