import {chromium} from 'playwright';
import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
import {AIService} from '../packages/ai-service/index.ts';import {startServer} from '../apps/local-server/server.ts';import {validate} from '../packages/document-core/index.ts';
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'zhitu-polish-'));
const ai=await new AIService(dir,async(_file,args,o)=>{
 const xml=o.input!.split('当前完整图稿：\n')[1].split('\n用户需求：')[0];
 let answer=xml.replace('value="订单服务"','value="订单处理服务"');
 if(o.input!.includes('大图验证')){let nodes='';for(let i=0;i<55;i++)nodes+=`<mxCell id="test-${i}" value="独立节点 ${i}" vertex="1" parent="1" style="rounded=1;fillColor=#eaf2ff;strokeColor=#4c78b8;fontFamily=Noto Sans SC;"><mxGeometry x="${(i%8)*140}" y="${800+Math.floor(i/8)*90}" width="120" height="60" as="geometry"/></mxCell>`;answer=answer.replace('</root>',nodes+'</root>');}
 await fs.writeFile(args[args.indexOf('-o')+1],answer);return '{}';
}).init();await ai.save({defaultProvider:'codex',providers:{codex:{path:process.execPath,model:''},qoder:{path:process.execPath,model:''}}});
const server=await startServer({port:0,aiService:ai}),browser=await chromium.launch({channel:'chromium'}),context=await browser.newContext({viewport:{width:1440,height:900},acceptDownloads:true}),page=await context.newPage();
const checks:string[]=[],errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const check=(s:string)=>{checks.push(s);console.log('PASS',s);};
try{
 await page.goto(server.origin);await page.getByText('9 个节点 · 6 条连线').waitFor();const frame=page.frames()[1];
 const invoke=(method:string,args:any={})=>frame.evaluate(({method,args})=>(window as any).workbench.invoke(method,args),{method,args});
 const original=await invoke('snapshot'),base=validate(original.xml);const snap=async()=>validate((await invoke('snapshot')).xml);
 await page.getByRole('button',{name:'◉ 主题配色',exact:true}).click();assert.equal(await page.getByRole('dialog',{name:'图稿主题配色'}).locator('.theme-grid button').count(),10);const gallery=await page.getByRole('dialog',{name:'图稿主题配色'}).boundingBox();for(const card of await page.locator('.theme-grid button').all()){const r=await card.boundingBox();assert.ok(r!.x+r!.width<=gallery!.x+gallery!.width);}await page.screenshot({path:'artifacts/theme-gallery.png'});await page.getByLabel('关闭主题配色').click();
 for(const name of ['default','architecture','flow','ocean','indigo','rose','clay','teal','slate','contrast']){
  await invoke('preset',{name,all:true});const after=await snap();assert.ok(after.ok);assert.deepEqual(after.cells!.map(c=>[c.id,c.label,c.kind,c.parent,c.source,c.target,c.geometry]),base.cells!.map(c=>[c.id,c.label,c.kind,c.parent,c.source,c.target,c.geometry]));await invoke('action',{name:'undo'});assert.equal((await snap()).contentHash,base.contentHash);
 }
 check('10 themes preserve node structure, connections, labels and geometry, each undoable in one step');
 await invoke('focus',{ids:['service']});await page.waitForTimeout(100);
 await page.getByLabel('十六进制颜色').fill('#123456');await page.getByRole('button',{name:'用色',exact:true}).click();await page.getByRole('button',{name:'最近颜色 #123456',exact:true}).waitFor();assert.ok((await snap()).cells!.find(c=>c.id==='service')!.style.includes('fillColor=#123456'));
 await page.getByLabel('颜色作用对象').selectOption('fontColor');await page.getByRole('button',{name:'颜色 #ffffff',exact:true}).click();await page.waitForTimeout(100);assert.ok((await snap()).cells!.find(c=>c.id==='service')!.style.includes('fontColor=#ffffff'));
 await page.getByRole('button',{name:'复制样式',exact:true}).click();await page.waitForTimeout(100);await invoke('focus',{ids:['inventory']});await page.waitForTimeout(100);const beforePaste=await snap();await page.getByRole('button',{name:'粘贴样式',exact:true}).click();await page.waitForTimeout(120);const afterPaste=await snap();assert.ok(afterPaste.cells!.find(c=>c.id==='inventory')!.style.includes('fillColor=#123456'));assert.deepEqual(afterPaste.cells!.map(c=>[c.id,c.label,c.geometry,c.source,c.target]),beforePaste.cells!.map(c=>[c.id,c.label,c.geometry,c.source,c.target]));await invoke('action',{name:'undo'});assert.equal((await snap()).contentHash,beforePaste.contentHash);
 check('custom/quick colors update targets and recent colors; appearance copy preserves content and can undo');
 const second=await context.newPage();await second.goto(server.origin);await second.getByText('9 个节点 · 6 条连线').waitFor();assert.ok(await second.getByLabel('最近使用颜色').getByRole('button',{name:'最近颜色 #123456',exact:true}).count());await second.close();check('recent colors survive a new page on the same browser context');
 await invoke('load',{xml:original.xml});await invoke('focus',{ids:['client']});await invoke('action',{name:'lockUnlock'});const locked=(await snap()).cells!.find(c=>c.id==='client')!;await invoke('preset',{name:'ocean',all:true});assert.equal((await snap()).cells!.find(c=>c.id==='client')!.style,locked.style);await assert.rejects(invoke('color',{key:'fillColor',value:'#112233'}),/选择/);check('theme and color operations respect locked objects');
 await invoke('load',{xml:original.xml});await invoke('focus',{ids:['service','inventory','queue']});const beforeArrange=await snap();for(const action of ['left','center','right','top','middle','bottom','horizontal','vertical']){await invoke('focus',{ids:['service','inventory','queue']});await invoke('arrange',{action});assert.ok((await snap()).ok);await invoke('action',{name:'undo'});assert.equal((await snap()).contentHash,beforeArrange.contentHash);}
 await invoke('focus',{ids:['service','client']});await assert.rejects(invoke('arrange',{action:'left'}),/同一容器/);check('all alignment/distribution actions are valid and undoable; cross-container movement is refused');
 // Load a real editor baseline with a font which normalization maps to the bundled font.
 await invoke('load',{xml:original.xml.replaceAll('fontFamily=Noto Sans SC','fontFamily=Arial')});
 await page.getByRole('button',{name:'AI 会话',exact:true}).click();const panel=page.getByRole('complementary',{name:'AI 会话'});
 await panel.getByLabel('AI 绘图要求').fill('大图验证：保留当前图稿并补充独立节点');await panel.getByRole('button',{name:'发送给 AI',exact:true}).click();await panel.getByText(/项变化 · 待应用/).waitFor();
 // An edit followed by undo restores the exact content but advances revision.
 await invoke('focus',{ids:['service']});await invoke('color',{key:'fillColor',value:'#654321'});await invoke('action',{name:'undo'});await invoke('zoom',{action:'in'});
 await panel.getByRole('button',{name:'预览候选',exact:true}).click();const dialog=page.getByRole('dialog',{name:'候选大图预览'});await dialog.waitFor();await dialog.getByRole('status').waitFor();const img=dialog.getByAltText('AI 生成候选预览');await img.waitFor();await img.evaluate((i:HTMLImageElement)=>i.decode());const box=await dialog.boundingBox(),imageBox=await img.boundingBox();assert.ok(imageBox!.height>100);assert.ok(imageBox!.y>=box!.y&&imageBox!.y+imageBox!.height<=box!.y+box!.height);await page.screenshot({path:'artifacts/large-candidate-preview.png'});
 await dialog.getByRole('button',{name:'缩小预览',exact:true}).click();assert.ok((await img.boundingBox())!.width<imageBox!.width);await dialog.getByRole('button',{name:'放大预览',exact:true}).click();await dialog.getByRole('button',{name:'适应预览',exact:true}).click();await dialog.getByRole('button',{name:'应用此候选',exact:true}).click();await panel.getByText('候选已应用，可一步撤销').waitFor();assert.equal((await snap()).stats.nodes,64);await invoke('action',{name:'undo'});assert.equal((await snap()).contentHash,base.contentHash);
 check('55 added nodes preview visibly in a large dialog and apply after font normalization, zoom and edit/undo; undo restores original');
 // Inject an export failure: a visible error, retry and download must work without regenerating AI.
 await panel.getByLabel('AI 绘图要求').fill('将订单服务改为订单处理服务');await panel.getByRole('button',{name:'发送给 AI',exact:true}).click();await panel.getByText(/项变化 · 待应用/).waitFor();
 await page.route('**/api/exports',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'预览服务暂时不可用'})}));await panel.getByRole('button',{name:'预览候选',exact:true}).click();await dialog.getByRole('alert').waitFor();assert.ok((await dialog.innerText()).includes('预览服务暂时不可用'));await page.unroute('**/api/exports');await dialog.getByRole('button',{name:'重新预览',exact:true}).click();await dialog.getByAltText('AI 生成候选预览').waitFor();await dialog.getByLabel('关闭候选预览').click();
 const download=page.waitForEvent('download');await panel.getByRole('button',{name:'下载候选 .drawio',exact:true}).click();const d=await download;assert.ok(validate(await fs.readFile((await d.path())!,'utf8')).ok);
 await invoke('focus',{ids:['service']});await invoke('color',{key:'fillColor',value:'#345678'});const edited=await snap();await panel.getByRole('button',{name:'应用到画布',exact:true}).click();const conflictDialog=page.getByRole('dialog',{name:'图稿已变化',exact:true});await conflictDialog.waitFor();assert.equal((await snap()).contentHash,edited.contentHash);await conflictDialog.getByRole('button',{name:'保留当前图稿',exact:true}).click();assert.equal(await panel.getByRole('button',{name:'下载候选 .drawio',exact:true}).isEnabled(),true);
 check('preview errors are visible and retryable; candidate downloads survive real editing conflicts without overwriting canvas');
 assert.deepEqual(errors,[]);check('all new flows have no browser runtime errors');
 await fs.writeFile('artifacts/product-polish-results.json',JSON.stringify({ok:true,checks},null,2));
}finally{await browser.close();await server.close();await fs.rm(dir,{recursive:true,force:true});}
