import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
import {AIService,type Provider} from '../packages/ai-service/index.ts';import {emptyDocument,validate} from '../packages/document-core/index.ts';
const p=process.argv[2] as Provider;const dir=await fs.mkdtemp(path.join(os.tmpdir(),'zhitu-capability-'));const ai=await new AIService(dir).init();if(process.env.ZHITU_CODEX_PATH)ai.config.providers.codex.path=process.env.ZHITU_CODEX_PATH;if(p === "qoder" && process.argv[3]) ai.config.providers.qoder.model=process.argv[3];const checks:any[]=[];
try{
 const task=ai.generate({provider:p,prompt:'忠实还原附件流程图的文字、节点、连线方向，所有对象独立可编辑。',xml:emptyDocument('截图会话验证'),revision:0,mode:'generate',image:{mime:'image/png',data:(await fs.readFile('fixtures/benchmark/images/01-flow.png')).toString('base64')}});
 await ai.jobs.get(task.id)!.done;const result=ai.view(task.id);assert.equal(result.status,'succeeded',result.error);const validation=validate(result.result!.candidateXml!);assert.ok(validation.stats.nodes>=3);assert.ok(validation.stats.edges>=2);await fs.writeFile(`artifacts/chat-${p}-screenshot.drawio`,result.result!.candidateXml!);checks.push({kind:'screenshot',status:'passed',model:result.model,elapsedMs:result.finishedAt!-result.createdAt,progress:result.progress,nodes:validation.stats.nodes,edges:validation.stats.edges});console.log(p,'screenshot passed');
 const target=validation.cells!.find(c=>c.kind==='node'&&c.label.trim())!;
 const edit=ai.generate({provider:p,prompt:`仅将对象 ${target.id} 的文字修改为「会话修改验证」，其余布局、文字、样式和关系保持不变。`,xml:validation.xml!,revision:1,mode:'selection',selection:[target.id],history:[{user:'还原截图',assistant:'已生成并应用'}]});
 await ai.jobs.get(edit.id)!.done;const changed=ai.view(edit.id);assert.equal(changed.status,'succeeded',changed.error);assert.ok(changed.result!.changes.some(c=>c.id===target.id&&c.kind==='文字'&&c.after==='会话修改验证'));assert.ok(changed.result!.changes.every(c=>c.id===target.id));await fs.writeFile(`artifacts/chat-${p}-edit.drawio`,changed.result!.candidateXml!);checks.push({kind:'selection edit',status:'passed',changes:changed.result!.changes.length});console.log(p,'edit passed');
} catch(e){checks.push({status:'failed',error:(e as Error).message});console.error((e as Error).message);process.exitCode=1;}finally{await fs.writeFile(`artifacts/chat-${p}-capabilities.json`,JSON.stringify(checks,null,2));await ai.close();await fs.rm(dir,{recursive:true,force:true});}
